package apresentacao;


import java.awt.Component;
import negocio.Quarto;
import negocio.Pousada;
import negocio.Chale;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author vinicius.andrade
 */
public class Atualizar extends javax.swing.JFrame {
  Pousada pousada;
    /**
     * Creates new form Atualizar
     */
    public Atualizar() {
        pousada = Pousada.getInstance();
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNumQuarto = new javax.swing.JTextField();
        txtNumChale = new javax.swing.JTextField();
        btVisualizarPrecoAtualChale = new javax.swing.JToggleButton();
        btGravarPrecoNovoChale = new javax.swing.JToggleButton();
        txtPrecoQuarto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPrecoChale = new javax.swing.JTextField();
        btSair = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        btVisualizarPrecoAtualQuarto = new javax.swing.JButton();
        btGravarPrecoNovoQuarto = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Atualizar dados"));

        jLabel1.setText("Quarto:");

        jLabel2.setText("Chalé:");

        btVisualizarPrecoAtualChale.setText("Visualizar Preço Atual");
        btVisualizarPrecoAtualChale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVisualizarPrecoAtualChaleActionPerformed(evt);
            }
        });

        btGravarPrecoNovoChale.setText("Gravar Preço Novo");
        btGravarPrecoNovoChale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarPrecoNovoChaleActionPerformed(evt);
            }
        });

        jLabel3.setText("Preço:");

        jLabel4.setText("Preço:");

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Cancel-32.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/new-32.png"))); // NOI18N
        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btVisualizarPrecoAtualQuarto.setText("Visualizar Preço Atual");
        btVisualizarPrecoAtualQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVisualizarPrecoAtualQuartoActionPerformed(evt);
            }
        });

        btGravarPrecoNovoQuarto.setText("Gravar Preço Novo");
        btGravarPrecoNovoQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarPrecoNovoQuartoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btVisualizarPrecoAtualQuarto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btVisualizarPrecoAtualChale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btGravarPrecoNovoChale, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumChale, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPrecoQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btGravarPrecoNovoQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtPrecoChale, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecoQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVisualizarPrecoAtualQuarto)
                    .addComponent(btGravarPrecoNovoQuarto))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumChale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtPrecoChale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVisualizarPrecoAtualChale)
                    .addComponent(btGravarPrecoNovoChale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSair)
                    .addComponent(btNovo))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btVisualizarPrecoAtualChaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVisualizarPrecoAtualChaleActionPerformed
        // TODO add your handling code here:
        if (!txtNumChale.getText().isEmpty()) {
            int numeroChale = -1;
            try{
                numeroChale = Integer.parseInt(txtNumChale.getText())-1;
            }catch (Exception ex){
                JOptionPane.showMessageDialog(this, "Caractere inválido. Digite o número do Chalé");
                return;
            }
            
            if(numeroChale < 0 || numeroChale > pousada.getChales().size() ){
                JOptionPane.showMessageDialog(null, "Digite um numero entre 1 e " + (pousada.getChales().size()) );
            }else{
                Chale c = pousada.getChales().get(numeroChale);
                txtPrecoChale.setText(String.valueOf(c.getPreco()));
            }
        }else{
            JOptionPane.showMessageDialog(this, "Campo vazio. Por favor digite um número.");
        }       
    }//GEN-LAST:event_btVisualizarPrecoAtualChaleActionPerformed

    private void btGravarPrecoNovoChaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarPrecoNovoChaleActionPerformed
        // TODO add your handling code here:
        if (!txtNumChale.getText().isEmpty()) {
            int numeroChale = -1;
            try{
                numeroChale = Integer.parseInt(txtNumChale.getText()) - 1;
            }catch (Exception ex){
                JOptionPane.showMessageDialog(this, "Caractere inválido. Digite o número do Chalé");
                return;
            }
            
            if(numeroChale < 0 || numeroChale > pousada.getChales().size() ){
                JOptionPane.showMessageDialog(null, "Digite um numero entre 1 e " + (pousada.getChales().size()) );
            }else{
                Chale c = pousada.getChales().get(numeroChale);
                c.setPreco(Double.parseDouble(txtPrecoChale.getText()));
            }
        }else{
            JOptionPane.showMessageDialog(this, "Campo vazio. Por favor digite um número.");
        }
    }//GEN-LAST:event_btGravarPrecoNovoChaleActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_btNovoActionPerformed

    private void btVisualizarPrecoAtualQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVisualizarPrecoAtualQuartoActionPerformed
        // TODO add your handling code here:
        if (!txtNumQuarto.getText().isEmpty()) {
            int numeroQuarto = -1;
            try{
                numeroQuarto = Integer.parseInt(txtNumQuarto.getText()) - 1;
            }catch (Exception ex){
                JOptionPane.showMessageDialog(this, "Caractere inválido. Digite o número do Quarto");
                return;
            }
            
            if(numeroQuarto < 0 || numeroQuarto > pousada.getQuartos().size() ){
                JOptionPane.showMessageDialog(null, "Digite um numero entre 1 e " + (pousada.getQuartos().size()) );
            }else{
                Quarto q = pousada.getQuartos().get(numeroQuarto);
                txtPrecoQuarto.setText(String.valueOf(q.getPreco()));
            }
        }else{
            JOptionPane.showMessageDialog(this, "Campo vazio. Por favor digite um número.");
        }
    }//GEN-LAST:event_btVisualizarPrecoAtualQuartoActionPerformed

    private void btGravarPrecoNovoQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarPrecoNovoQuartoActionPerformed
        // TODO add your handling code here:
        if (!txtNumQuarto.getText().isEmpty()) {
            int numeroQuarto = -1;
            try{
                numeroQuarto = Integer.parseInt(txtNumQuarto.getText()) - 1;
            }catch (Exception ex){
                JOptionPane.showMessageDialog(this, "Caractere inválido. Digite o número do Quarto");
                return;
            }
            
            if(numeroQuarto < 0 || numeroQuarto > pousada.getQuartos().size() ){
                JOptionPane.showMessageDialog(null, "Digite um numero entre 1 e " + (pousada.getQuartos().size()) );
            }else{
                Quarto q = pousada.getQuartos().get(numeroQuarto);
                q.setPreco(Double.parseDouble( txtPrecoQuarto.getText() ));
            }
        }else{
            JOptionPane.showMessageDialog(this, "Campo vazio. Por favor digite um número.");
        }
    }//GEN-LAST:event_btGravarPrecoNovoQuartoActionPerformed

    private void limpar(){
        Component components[] = jPanel1.getComponents();  
        for (Component component : components)  
        {  
            if (component instanceof JTextField)  
            {  
                ((JTextField)component).setText(null);  
            }  
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Atualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Atualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Atualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Atualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Atualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btGravarPrecoNovoChale;
    private javax.swing.JButton btGravarPrecoNovoQuarto;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSair;
    private javax.swing.JToggleButton btVisualizarPrecoAtualChale;
    private javax.swing.JButton btVisualizarPrecoAtualQuarto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNumChale;
    private javax.swing.JTextField txtNumQuarto;
    private javax.swing.JTextField txtPrecoChale;
    private javax.swing.JTextField txtPrecoQuarto;
    // End of variables declaration//GEN-END:variables
}
