package apresentacao;

import negocio.Cliente;
import negocio.RegistrosAlugueis;
import negocio.Pousada;
import negocio.Aluguel;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author vinicius.andrade
 */
public class Checkin extends javax.swing.JFrame {

    /**
     * Creates new form Checkin
     */
    public Checkin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextNome = new javax.swing.JTextField();
        jComboBoxTipoAcomodacao = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jTextCamasExtars = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Recanto de Maraú", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18), new java.awt.Color(0, 153, 102))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Chek in");

        jLabel2.setText("Nome: ");

        jComboBoxTipoAcomodacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Quarto com Banheira", "Quarto sem Banheira", "Chalé", " " }));
        jComboBoxTipoAcomodacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoAcomodacaoActionPerformed(evt);
            }
        });

        jLabel3.setText("Camas extras");

        jTextCamasExtars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCamasExtarsActionPerformed(evt);
            }
        });

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane1.setViewportView(jTextArea);

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBoxTipoAcomodacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextCamasExtars, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTipoAcomodacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextCamasExtars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // inicializa campos;
        Boolean paraTudo = true;
        RegistrosAlugueis registroAlugueis = RegistrosAlugueis.getInstance();
        Aluguel aluguel = new Aluguel();
        //VALIDA CAMPOS 
        if (jTextNome.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite um nome");
                return;
        }
         Aluguel aluguel2 = new Aluguel();   
        try {
            aluguel2 = registroAlugueis.getAlugueis().get(registroAlugueis.buscaAluguel(jTextNome.getText()));           
        } catch (Exception ex) {
            paraTudo = false;           
        }
   
        if (paraTudo) {
            JOptionPane.showMessageDialog(this, "No momento só alugamos uma instalação por pessoa");
        }
        
        Pousada pousada = Pousada.getInstance();
        //Localiza quarto Disponível
        if (jComboBoxTipoAcomodacao.getSelectedItem() == "Quarto com Banheira") {
            int i;
//verifica os quartos
            for (i = 0; i < pousada.getQuantQuartos(); i++) {
                // se achou um quarto com banheira
                if ((pousada.buscaQuarto(i).isReservado() == false) && (pousada.buscaQuarto(i).isTemBanheira())) {
                    //Mensagem
                    jTextArea.setText("Reservamos o quarto" + (i + 1) + " com \nBanheira para o Cliente: \n" + jTextNome.getText());
                    //Instancia objetos que serão incluídos.
                    
                    Cliente cliente = new Cliente();
                    Date data = new Date();
                    
                    // Seta Atributos
                    data.setTime(data.getTime());
                    cliente.setNome(jTextNome.getText());
                    aluguel.setCliente(cliente);
                    aluguel.setQuarto(pousada.buscaQuarto(i));
                    aluguel.setDataEntrada(data);
                    aluguel.getQuarto().setReservado(true);                   
                    registroAlugueis.addAluguel(aluguel);
                    break;
                }
                jTextArea.setText(" Não existe quarto disponível.");
            }
        } else if (jComboBoxTipoAcomodacao.getSelectedItem() == "Quarto sem Banheira") {
            int i;
//verifica os quartos 
            for (i = 0; i < pousada.getQuantQuartos(); i++) {
                // se achou um quarto com banheira
                if ((pousada.buscaQuarto(i).isReservado() == false) && (pousada.buscaQuarto(i).isTemBanheira() == false)) {
                    //Mensagem
                    jTextArea.setText("Reservamos o quarto" + (i + 1) + " sem \nBanheira para o Cliente: \n" + jTextNome.getText());
                    //Instancia objetos que serão incluídos.
                   
                    Cliente cliente = new Cliente();
                    Date data = new Date();
                   
                    // Seta Atributos
                    data.setTime(data.getTime());
                    cliente.setNome(jTextNome.getText());
                    aluguel.setCliente(cliente);
                    aluguel.setQuarto(pousada.buscaQuarto(i));
                    aluguel.setDataEntrada(data);
                    aluguel.getQuarto().setReservado(true);
                    registroAlugueis.addAluguel(aluguel);
                    break;
                }
                jTextArea.setText(" Não existe quarto disponível.");
            }
        } else if (jComboBoxTipoAcomodacao.getSelectedItem() == "Chalé") {
            int i;
        try {
        Integer.parseInt(jTextCamasExtars.getText());
        }catch (Exception ex){
                JOptionPane.showMessageDialog(this, "Somente números são permitidos");
                return;
        }
        
//verifica os quartos 
            for (i = 0; i < pousada.getQuantChales(); i++) {
                // se achou um quarto com banheira
                if ((pousada.getChale(i).isReservado() == false) && (pousada.buscaQuarto(i).isTemBanheira() == false)) {
                        //Mensagem

                    if (jTextCamasExtars.getText().equals("")) {
                        jTextArea.setText("Reservamos o Chalé " + (i + 1) + " \npara o Cliente: " + jTextNome.getText());
                    } else {
                        jTextArea.setText("Reservamos o Chalé " + (i + 1) + "\n"
                                + "com  " + jTextCamasExtars.getText() + " camas extras \npara o Cliente: " + jTextNome.getText());
                    }

//Instancia objetos que serão incluídos.
                 
                    Cliente cliente = new Cliente();
                    Date data = new Date();
                  
                    // Seta Atributos
                    data.setTime(data.getTime());
                    cliente.setNome(jTextNome.getText());
                    aluguel.setCliente(cliente);
                    aluguel.setChale(pousada.getChale(i));
                    aluguel.setDataEntrada(data);
                    aluguel.getChale().setReservado(true);
                    if (jTextCamasExtars.getText().equals("")) {
                        aluguel.getChale().setCamasExtras(0);
                    } else {
                        aluguel.getChale().setCamasExtras(Integer.valueOf(jTextCamasExtars.getText()));
                    }
                    registroAlugueis.addAluguel(aluguel);
                    break;
                }
                jTextArea.setText(" Não existe quarto disponível.");
            }
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxTipoAcomodacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoAcomodacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoAcomodacaoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextCamasExtarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCamasExtarsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCamasExtarsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Checkin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Checkin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Checkin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Checkin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Checkin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBoxTipoAcomodacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JTextField jTextCamasExtars;
    private javax.swing.JTextField jTextNome;
    // End of variables declaration//GEN-END:variables
}
